### ISSUE TITLE
@supports inside of @media throws an Exception

### ISSUE THREAD

**Issue by DirkPersky** [hummal/crittr#34]
**Describe the bug**
Using [`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) css inside of `@media` throws an exception.
If u remove the Media Query it works.

**To Reproduce**
```
(async () => {
    const Crittr = require("crittr");
    try {
        const { critical, rest } = await Crittr({
            urls: _URLS_,
            css: `
               
            @charset "UTF-8";
            @media (min-width: 576px) {
                @supports (display: grid) {
                    div {
                        display: grid;
                      }
                }
            }
            `
        });

        console.log(critical);
    } catch (err) {
        console.error(err);
    }
})();
```

```
►  Crittr Run Initialized timer...
C:\Users\Dirk\Desktop\projekte\trash\above\node_modules\crittr\lib\classes\CssTransformator.class.js:140
internalRule.selectors = internalRule.selectors.filter(
                                                ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at C:\Users\Dirk\Desktop\projekte\trash\above\node_modules\crittr\lib\classes\CssTransformator.class.js:140:49
    at Array.map (<anonymous>)
    at C:\Users\Dirk\Desktop\projekte\trash\above\node_modules\crittr\lib\classes\CssTransformator.class.js:136:26
    at Array.map (<anonymous>)
    at CssTransformator.filterByMap (C:\Users\Dirk\Desktop\projekte\trash\above\node_modules\crittr\lib\classes\CssTransformator.class.js:130:44)
    at C:\Users\Dirk\Desktop\projekte\trash\above\node_modules\crittr\lib\classes\Crittr.class.js:747:71
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Screenshots**
![image](https://user-images.githubusercontent.com/1736266/162231615-be46e844-708d-497a-a080-ed5c0af0db90.png)

**Environment (please complete the following information):**
 - Windows

**Additional context**
I cant remove the `@media` `@supports` becouse it comes out of a vendor ( http://fancybox.net/ ) repository.

**Comment by hummal** [comment]
Thank you for the detailed report. I will see what I can do about that issue.

**Comment by hummal** [comment]
@DirkPersky I finished working on your request. Are you able to test the new version from github? Otherwise I will create a new beta version to test for you.

**Comment by hummal** [comment]
@DirkPersky any news on this?

**Comment by DirkPersky** [comment]
Yes, now it looks fine.
